import java.util.ArrayList;
public class PokeList
{
	Pokemon bulbasaur = new Pokemon("bulbasaur", 45);
	Pokemon ivasaur = new Pokemon("ivasaur", 45);
	Pokemon venasaur = new Pokemon("venasaur", 45);
	
	
	ArrayList<Pokemon> pokemonList = new ArrayList<Pokemon>();
	ArrayList<Pokemon> notFound = new ArrayList<Pokemon>();

	public ArrayList<Pokemon> createList()
	{
		pokemonList.add(bulbasaur);
		pokemonList.add(ivasaur);
		pokemonList.add(venasaur);
		pokemonList.add(new Pokemon("charmander", 45));
		pokemonList.add(new Pokemon("charmeleon", 45));
		pokemonList.add(new Pokemon("charizard", 45));
		pokemonList.add(new Pokemon("squirtle", 45));
		pokemonList.add(new Pokemon("wartortle", 45));
		pokemonList.add(new Pokemon("blastoise", 45));
		pokemonList.add(new Pokemon("caterpie", 255));
		pokemonList.add(new Pokemon("metapod", 120));
		pokemonList.add(new Pokemon("butterfree", 45));
		pokemonList.add(new Pokemon("weedle", 255));
		pokemonList.add(new Pokemon("kakuna", 120));
		pokemonList.add(new Pokemon("beedrill", 45));
		pokemonList.add(new Pokemon("pidgey", 255));
		pokemonList.add(new Pokemon("pidgeotto", 120));
		pokemonList.add(new Pokemon("pidgeot", 45));
		pokemonList.add(new Pokemon("rattata", 255));
		pokemonList.add(new Pokemon("raticate", 127));
		pokemonList.add(new Pokemon("spearow", 255));
		pokemonList.add(new Pokemon("fearow", 90));
		pokemonList.add(new Pokemon("ekans", 255));
		pokemonList.add(new Pokemon("arbok", 90));
		pokemonList.add(new Pokemon("pikachu", 190));
		pokemonList.add(new Pokemon("raichu", 75));
		pokemonList.add(new Pokemon("sandshrew", 255));
		pokemonList.add(new Pokemon("sandslash", 90));
		pokemonList.add(new Pokemon("nidoran", 235));
		pokemonList.add(new Pokemon("nidorina", 120));
		pokemonList.add(new Pokemon("nidoqueen", 45));
		pokemonList.add(new Pokemon("nidorino", 120));
		pokemonList.add(new Pokemon("nidoking", 45));
		pokemonList.add(new Pokemon("clefairy", 150));
		pokemonList.add(new Pokemon("clefable", 25));
		pokemonList.add(new Pokemon("vulpix", 190));
		pokemonList.add(new Pokemon("ninetails", 75));
		pokemonList.add(new Pokemon("jigglypuff", 170));
		pokemonList.add(new Pokemon("wigglytuff", 50));
		pokemonList.add(new Pokemon("zubat", 255));
		pokemonList.add(new Pokemon("golbat", 90));
		pokemonList.add(new Pokemon("oddish", 255));
		pokemonList.add(new Pokemon("gloom", 120));
		pokemonList.add(new Pokemon("vileplume", 45));
		pokemonList.add(new Pokemon("paras", 190));
		pokemonList.add(new Pokemon("parasect", 75));
		pokemonList.add(new Pokemon("venonat", 190));
		pokemonList.add(new Pokemon("venomoth", 75));
		pokemonList.add(new Pokemon("diglett", 255));
		pokemonList.add(new Pokemon("dugtrio", 50));
		pokemonList.add(new Pokemon("meowth", 255));
		pokemonList.add(new Pokemon("persian", 90));
		pokemonList.add(new Pokemon("psyduck", 190));
		pokemonList.add(new Pokemon("golduck", 75));
		pokemonList.add(new Pokemon("mankey", 190));
		pokemonList.add(new Pokemon("primeape", 75));
		pokemonList.add(new Pokemon("growlithe", 190));
		pokemonList.add(new Pokemon("arcanine", 75));
		pokemonList.add(new Pokemon("poliwag", 255));
		pokemonList.add(new Pokemon("poliwhirl", 120));
		pokemonList.add(new Pokemon("poliwrath", 45));
		pokemonList.add(new Pokemon("abra", 200));
		pokemonList.add(new Pokemon("kadabra", 100));
		pokemonList.add(new Pokemon("alakazam", 50));
		pokemonList.add(new Pokemon("machop", 180));
		pokemonList.add(new Pokemon("machoke", 90));
		pokemonList.add(new Pokemon("machamp", 45));
		pokemonList.add(new Pokemon("bellsprout", 255));
		pokemonList.add(new Pokemon("weepibell", 120));
		pokemonList.add(new Pokemon("victreebel", 120));
		pokemonList.add(new Pokemon("tentacool", 190));
		pokemonList.add(new Pokemon("tentacruel", 60));
		pokemonList.add(new Pokemon("geodude", 255));
		pokemonList.add(new Pokemon("graveler", 120));
		pokemonList.add(new Pokemon("golem", 45));
		pokemonList.add(new Pokemon("ponyta", 190));
		pokemonList.add(new Pokemon("rapidash", 60));
		pokemonList.add(new Pokemon("slowpoke", 190));
		pokemonList.add(new Pokemon("slowbro", 75));
		pokemonList.add(new Pokemon("magnemite", 190));
		pokemonList.add(new Pokemon("magneton", 60));
		pokemonList.add(new Pokemon("farfetchd", 45));
		pokemonList.add(new Pokemon("doduo", 45));
		pokemonList.add(new Pokemon("dodrio", 45));
		pokemonList.add(new Pokemon("seel", 190));
		pokemonList.add(new Pokemon("dewgong", 75));
		pokemonList.add(new Pokemon("grimer", 190));
		pokemonList.add(new Pokemon("muk", 75));
		pokemonList.add(new Pokemon("shellder", 190));
		pokemonList.add(new Pokemon("cloyster", 60));
		pokemonList.add(new Pokemon("gastly", 190));
		pokemonList.add(new Pokemon("haunter", 90));
		pokemonList.add(new Pokemon("gengar", 45));
		pokemonList.add(new Pokemon("onix", 45));
		pokemonList.add(new Pokemon("drowzee", 190));
		pokemonList.add(new Pokemon("hypno", 75));
		pokemonList.add(new Pokemon("krabby", 225));
		pokemonList.add(new Pokemon("kingler", 60));
		pokemonList.add(new Pokemon("voltorb", 190));
		pokemonList.add(new Pokemon("electrode", 60));
		pokemonList.add(new Pokemon("exeggcute", 90));
		pokemonList.add(new Pokemon("exeggutor", 45));
		pokemonList.add(new Pokemon("cubone", 190));
		pokemonList.add(new Pokemon("marowak", 75));
		pokemonList.add(new Pokemon("hitmonlee", 45));
		pokemonList.add(new Pokemon("hitmonchan", 45));
		pokemonList.add(new Pokemon("lickitung", 45));
		pokemonList.add(new Pokemon("koffing", 190));
		pokemonList.add(new Pokemon("weezing", 60));
		pokemonList.add(new Pokemon("ryhorn", 120));
		pokemonList.add(new Pokemon("rhydon", 60));
		pokemonList.add(new Pokemon("chansey", 30));
		pokemonList.add(new Pokemon("tangela", 45));
		pokemonList.add(new Pokemon("kangaskhan", 45));
		pokemonList.add(new Pokemon("horsea", 225));
		pokemonList.add(new Pokemon("seadra", 75));
		pokemonList.add(new Pokemon("goldeen", 225));
		pokemonList.add(new Pokemon("seaking", 60));
		pokemonList.add(new Pokemon("staryu", 225));
		pokemonList.add(new Pokemon("starmie", 60));
		pokemonList.add(new Pokemon("mrmime", 45));
		pokemonList.add(new Pokemon("scyther", 45));
		pokemonList.add(new Pokemon("jynx", 45));
		pokemonList.add(new Pokemon("electabuzz", 45));
		pokemonList.add(new Pokemon("magmar", 45));
		pokemonList.add(new Pokemon("pinsir", 45));
		pokemonList.add(new Pokemon("tauros", 45));
		pokemonList.add(new Pokemon("magikarp", 255));
		pokemonList.add(new Pokemon("gyarados", 45));
		pokemonList.add(new Pokemon("lapras", 45));
		pokemonList.add(new Pokemon("ditto", 35));
		pokemonList.add(new Pokemon("eevee", 45));
		pokemonList.add(new Pokemon("vaporeon", 45));
		pokemonList.add(new Pokemon("jolteon", 45));
		pokemonList.add(new Pokemon("flareon", 45));
		pokemonList.add(new Pokemon("porygon", 45));
		pokemonList.add(new Pokemon("omanyte", 45));
		pokemonList.add(new Pokemon("omastar", 45));
		pokemonList.add(new Pokemon("kabuto", 45));
		pokemonList.add(new Pokemon("kabutops", 45));
		pokemonList.add(new Pokemon("aerodactyl", 45));
		pokemonList.add(new Pokemon("snorlax", 25));
		pokemonList.add(new Pokemon("articuno", 3));
		pokemonList.add(new Pokemon("zapdos", 3));
		pokemonList.add(new Pokemon("moltres", 3));
		pokemonList.add(new Pokemon("dratini", 45));
		pokemonList.add(new Pokemon("dragonair", 45));
		pokemonList.add(new Pokemon("dragonite", 45));
		pokemonList.add(new Pokemon("mewtwo", 3));
		pokemonList.add(new Pokemon("mew", 35));
		return pokemonList;
	}
	
	public ArrayList<Pokemon> createNotFound()
	{
		return notFound;
	}
	
}
